# Installs PowerShell profile stubs for the dotfiles repo.
#
# Why stubs and not symlinks: when $PROFILE resolves under OneDrive-redirected
# Documents, Windows blocks reparse-point traversal there ("untrusted mount
# point"). A plain .ps1 file isn't a reparse point, so it loads cleanly and
# then dot-sources the real profile from this repo.

$ErrorActionPreference = 'Stop'

$source = Join-Path $PSScriptRoot 'Profile.ps1'
if (-not (Test-Path -LiteralPath $source)) {
    throw "Dotfiles profile not found at '$source'."
}
$source = (Resolve-Path -LiteralPath $source).Path

$stub = @"
# Auto-generated by $PSCommandPath
# Loads the dotfiles profile. Edit Profile.ps1 in the dotfiles repo, not this stub.
. '$source'
"@

$targets = @(
    $PROFILE.CurrentUserAllHosts,
    $PROFILE.CurrentUserCurrentHost
)

foreach ($dest in $targets) {
    $parent = Split-Path -Parent $dest
    if (-not (Test-Path -LiteralPath $parent)) {
        New-Item -ItemType Directory -Path $parent -Force | Out-Null
    }

    if (Test-Path -LiteralPath $dest) {
        $existing = Get-Item -Force -LiteralPath $dest
        if ($existing.Attributes -band [IO.FileAttributes]::ReparsePoint) {
            Remove-Item -Force -LiteralPath $dest
            Write-Host "Removed existing symlink at $dest" -ForegroundColor DarkGray
        } else {
            $backup = "$dest.bak-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
            Rename-Item -LiteralPath $dest -NewName (Split-Path -Leaf $backup)
            Write-Host "Backed up existing file to $backup" -ForegroundColor Yellow
        }
    }

    Set-Content -LiteralPath $dest -Value $stub -Encoding utf8
    Write-Host "Installed stub at $dest -> $source" -ForegroundColor Green
}

Write-Host ""
Write-Host "Done. Restart pwsh to verify." -ForegroundColor Cyan
